#!/command/with-contenv sh

[ -e /homebridge/lib/homebridge.log ] || touch /homebridge/lib/homebridge.log

chown homebridge:homebridge /homebridge/lib/homebridge.log

exec tail -f --follow=name /homebridge/lib/homebridge.log
