#!/command/with-contenv sh

export HOME=/home/homebridge
export USER=homebridge
export HOMEBRIDGE_CONFIG_UI=1

# this is not necessarily the ui version, it's now used as a feature compatibility indicator 
export CONFIG_UI_VERSION=4.44.2

# start homebridge
exec s6-setuidgid homebridge /opt/homebridge/start.sh
